/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "mobile-production": {
      type: "sst.aws.StaticSite";
      url: string;
    }
    "mobile-dev"?: {
      type: "sst.aws.StaticSite";
      url: string;
    };
  }
}

declare const sst: {
  Secret: new (name: string) => {
    value: string;
  };
};

declare const $app: {
  stage: string;
};

declare function $config(input: any): any;
